using System.Net;
using Domain.ArticleFeature.Services;
using Domain.CommentFeature.Models;
using Domain.Exceptions;
using Domain.UserFeature.Services;

namespace Domain.CommentFeature.Services;

public class CommentService : ICommentService
{
    private readonly ICommentRepository _commentRepository;
    private readonly IUserRepository _userRepository;
    private readonly IArticleRepository _articleRepository;

    public CommentService(ICommentRepository commentRepository,
        IUserRepository userRepository,
        IArticleRepository articleRepository)
    {
        _commentRepository = commentRepository;
        _userRepository = userRepository;
        _articleRepository = articleRepository;
    }

    public async Task Create(Comment comment)
    {
        if (comment.Id == null)
            throw new ConduitException
                { Message = "Id must be empty, it's autogenerated", StatusCode = HttpStatusCode.BadRequest };
        if (!await _userRepository.ExistsByUsername(comment.Username))
            throw new ConduitException
                { Message = "No such username, make sure you're logged in", StatusCode = HttpStatusCode.BadRequest };
        if (!await _articleRepository.ExistsBySlug(comment.ArticleSlug))
            throw new ConduitException
                { Message = "No article with such Slug", StatusCode = HttpStatusCode.BadRequest };
        _commentRepository.Create(comment);
    }

    public async Task DeleteById(long id)
    { 
        await _commentRepository.DeleteById(id);
    }
}